// <auto-generated />
using System;
using Database.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Database.Migrations
{
    [DbContext(typeof(BaseDbContext))]
    [Migration("20250414070025_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("Database.Entities.MetadataEntity", b =>
                {
                    b.Property<int>("TaskId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("TaskId");

                    b.ToTable("Metadata");
                });

            modelBuilder.Entity("Database.Entities.TagEntity", b =>
                {
                    b.Property<int>("MetadataId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tag")
                        .HasColumnType("TEXT");

                    b.HasKey("MetadataId", "Tag");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("Database.Entities.TaskCompositeEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("TaskComposites");
                });

            modelBuilder.Entity("Database.Entities.TaskElementEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("Deadline")
                        .HasColumnType("TEXT");

                    b.Property<int>("Difficult")
                        .HasColumnType("INTEGER");

                    b.Property<double>("ExecutedReal")
                        .HasColumnType("REAL");

                    b.Property<double>("PlannedReal")
                        .HasColumnType("REAL");

                    b.Property<TimeSpan>("PlannedTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Progress")
                        .HasColumnType("REAL");

                    b.Property<TimeSpan>("SpentTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("TaskElements");
                });

            modelBuilder.Entity("Database.Entities.TaskEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ParentTaskId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ParentTaskId");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("Database.Entities.TimeIntervalEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("End")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Start")
                        .HasColumnType("TEXT");

                    b.Property<int>("TaskElementId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TaskElementId");

                    b.ToTable("TimeIntervals");
                });

            modelBuilder.Entity("Database.Entities.MetadataEntity", b =>
                {
                    b.HasOne("Database.Entities.TaskEntity", "Task")
                        .WithOne("Metadata")
                        .HasForeignKey("Database.Entities.MetadataEntity", "TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Task");
                });

            modelBuilder.Entity("Database.Entities.TagEntity", b =>
                {
                    b.HasOne("Database.Entities.MetadataEntity", "Metadata")
                        .WithMany("Tags")
                        .HasForeignKey("MetadataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Metadata");
                });

            modelBuilder.Entity("Database.Entities.TaskCompositeEntity", b =>
                {
                    b.HasOne("Database.Entities.TaskEntity", "Task")
                        .WithOne("TaskComposite")
                        .HasForeignKey("Database.Entities.TaskCompositeEntity", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Task");
                });

            modelBuilder.Entity("Database.Entities.TaskElementEntity", b =>
                {
                    b.HasOne("Database.Entities.TaskEntity", "Task")
                        .WithOne("TaskElement")
                        .HasForeignKey("Database.Entities.TaskElementEntity", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Task");
                });

            modelBuilder.Entity("Database.Entities.TaskEntity", b =>
                {
                    b.HasOne("Database.Entities.TaskCompositeEntity", "ParentTask")
                        .WithMany("Subtasks")
                        .HasForeignKey("ParentTaskId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("ParentTask");
                });

            modelBuilder.Entity("Database.Entities.TimeIntervalEntity", b =>
                {
                    b.HasOne("Database.Entities.TaskElementEntity", "TaskElement")
                        .WithMany("TimeIntervals")
                        .HasForeignKey("TaskElementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaskElement");
                });

            modelBuilder.Entity("Database.Entities.MetadataEntity", b =>
                {
                    b.Navigation("Tags");
                });

            modelBuilder.Entity("Database.Entities.TaskCompositeEntity", b =>
                {
                    b.Navigation("Subtasks");
                });

            modelBuilder.Entity("Database.Entities.TaskElementEntity", b =>
                {
                    b.Navigation("TimeIntervals");
                });

            modelBuilder.Entity("Database.Entities.TaskEntity", b =>
                {
                    b.Navigation("Metadata")
                        .IsRequired();

                    b.Navigation("TaskComposite");

                    b.Navigation("TaskElement");
                });
#pragma warning restore 612, 618
        }
    }
}
